FROM python:3.10-slim

WORKDIR /app

COPY services/orders-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/orders-api/app ./app

RUN useradd -m appuser
USER appuser

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
